config/routes.rb
Rails.application.routes.draw do
  get 'stores/new'

  get 'products/new'

  devise_for :users

  root "pages#home"
  get "/home", to: "pages#home"
  get "/help", to: "pages#help"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
  get "/pricing", to: "pages#pricing"
  get "/delivery", to: "pages#delivery"

  resources :users, only: :show
  resources :products
  resources :stores

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: {maximum: 80}
  validates :address, presence: true, length: {maximum: 150}
  validates :phone, presence: true, length: {maximum: 20}

  def create
  end

  private

  def get_owner
  	self.user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_one :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end

  def products; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end
  def new
  end

  def show
  	@product = Product.find_by id: params[:id]
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def new
    @store = Store.new
  end

  def show
    @store = Store.find_by id: params[:id]
  end

  def create
  	@store = current_user.build_store store_params
  	if @store.save
  	  flash[:info] = "Da tao cua hang thanh cong"
      redirect_to current_user
  	else
      render :new
  	end
  end

  private

  def store_params
    params.require(:store).permit :name, :address, :phone
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = User.find_by id: params[:id]
		return if @user
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/contents/_about_top.html.erb
<div class="about-top">
  <div class="col span_1_of_about">
    <h3>About</h3>
      <div class="about-img">
        <img src="images/pic8.jpg" alt=""/>
      </div>
  <div class="about-desc">
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate.</p>
  </div>
  <div class="clear"></div>
  </div>
  <div class="col span_1_of_about1">
  <h3>Recent Comments</h3>
    <ul class="comments-custom unstyled">
      <li class="comments-custom_li">
        <div class="icon"></div>
          <div class="right-text">
            <h4 class="comments-custom_h">admin:</h4>
              <div class="comments-custom_txt">
                <a href="#" title="Go to this comment">Sed ut perspiciatis unde omnis iste...</a>
              </div>
            <time>May 05,2013</time>
          </div>
       <div class="clear"></div>
       </li>
      <li class="comments-custom_li">
        <div class="icon"></div>
          <div class="right-text">
            <h4 class="comments-custom_h">admin:</h4>
              <div class="comments-custom_txt">
                <a href="#" title="Go to this comment">Sed ut perspiciatis unde omnis iste...</a>
              </div>
            <time>May 05,2013</time>
          </div>
        <div class="clear"></div>
      </li>
      <li class="comments-custom_li">
        <div class="icon"></div>
          <div class="right-text">
            <h4 class="comments-custom_h">admin:</h4>
              <div class="comments-custom_txt">
                <a href="#" title="Go to this comment">Sed ut perspiciatis unde omnis iste...</a>
              </div>
            <time>May 05,2013</time>
          </div>
        <div class="clear"></div>
      </li>
    </ul>
  </div>
  <div class="clear"></div>
</div>

app/views/contents/_content_bottom.html.erb
<div class="content-bottom">
  <div class="col_1_of_3 span_1_of_3">
    <img src="images/pic5.jpg" alt=""/>
      <div class="bottom-head"><h5>Lorem ipsum dolor sit amet, consectetuer</h5></div>
        <div class="but">
          <button class="btn1 btn-8 btn-8a">Read More</button>
        </div>
  </div>
  <div class="col_1_of_3 span_1_of_3">
    <img src="images/pic6.jpg" alt=""/>
      <div class="bottom-head"><h5>Lorem ipsum dolor sit amet, consectetuer</h5></div>
        <div class="but">
          <button class="btn1 btn-8 btn-8a">Read More</button>
        </div>
  </div>
  <div class="col_1_of_3 span_1_of_3">
    <img src="images/pic7.jpg" alt=""/>
      <div class="bottom-head"><h5>Lorem ipsum dolor sit amet, consectetuer</h5></div>
        <div class="but">
          <button class="btn1 btn-8 btn-8a">Read More</button>
        </div>
  </div>
  <div class="clear"></div>
</div>

app/views/contents/_content_example.html.erb
<div class="section group example">
				<div class="col_1_of_2 span_1_of_2">
				   <h3>Chief of the week</h3>
				   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugai consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
 				</div>
				<div class="col_1_of_2 span_1_of_2">
					<div class="grid1">
				<h3 class="head">Today's Offer-20%</h3>
				<p class="paragraph">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo cons</p>
				<button class="btn1 btn-8 btn-8a">Order Now</button>
				</div>	
				<ul class="hover-img">
					<li>
						<a href="#" class="sample-border2" style="position: relative;">
							<img src="images/pic17.jpg" alt=""/>
						<div class="border-effect" style="position: absolute; display: block; border: 0px solid rgb(255, 255, 255); top: 0px; bottom: 0px; right: 0px; left: 0px; opacity: 0; z-index: 100;"></div></a>
					</li>
				</ul>
			</div>
				<div class="clear"></div>
		    </div>

app/views/contents/_content_last.html.erb
<div class="content-last">
  <div class="col_1_of_4 span_1_of_4">
    <img src="images/glass.png" alt=""/>
      <h3>Lorem Ipsum is simply</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <button class="btn1 btn-8 btn-8a">Read More</button>
  </div>
  <div class="col_1_of_4 span_1_of_4">
    <img src="images/plate.png" alt=""/>
    <h3>Lorem Ipsum is simply</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <button class="btn1 btn-8 btn-8a">Read More</button>
  </div>
  <div class="col_1_of_4 span_1_of_4">
    <img src="images/icecream.png" alt=""/>
    <h3>Lorem Ipsum is simply</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <button class="btn1 btn-8 btn-8a">Read More</button>
  </div>
  <div class="col_1_of_4 span_1_of_4">
    <img src="images/leaf.png" alt=""/>
      <h3>Lorem Ipsum is simply</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <button class="btn1 btn-8 btn-8a">Read More</button>
  </div>
  <div class="clear"></div>
</div>

app/views/contents/_content_middle.html.erb
<div class="content-middle">
  <div class="col_1_of_2 span_1_of_2">
    <h3><span class="red">Lorem ipsum </span><br><span class="black">consectetuer</span></h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <button class="btn1 btn-8 btn-8a">Read More</button>
  </div>
  <div class="col_1_of_2 span_1_of_2">
    <div class="grid_img">
      <div class="hover_img">
        <img src="images/pic4.jpg" alt=""/>
      </div>
    </div>
    <div class="banner2">
      <a href="#">
        <div class="price">$50</div>
          <strong>Free Shipping</strong>
		  *eiusmod tempor incididunt ut labore
      </a>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/contents/_content_pricing.html.erb
<div class="pricing">
  <div class="col_1_of_3 span_1_of_3">
    <div class="inner-block">
      <h3 class="top-2">Lorem ipsum dolo</h3>
      <ul class="list-1 top-1 bot-2">
        <li><a href="#">Lorem ipsum dolor....................</a><span>$25.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Praesent vestibulum molestie.....</a><span>$8.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nonummy hendrerit</a><span>$19.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Porta fusce suscipit varius miursu</a><span>$21.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Etiam cursus leo vel metus</a><span>$15.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nec eros</a><span>$9.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Vestibulum ante ipsum primis</a><span>$12.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">In faucibus orci luctus et</a><span>$22.00</span><strong>&nbsp;</strong></li>
      </ul>
      <h3>consectetuer</h3>
      <ul class="list-1 top-4">
        <li><a href="#">Lorem ipsum dolor</a><span>$25.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Praesent vestibulum molestie</a><span>$8.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nonummy hendrerit</a><span>$19.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Porta fusce suscipit varius miursu</a><span>$21.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Etiam cursus leo vel metus</a><span>$15.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nec eros</a><span>$9.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Vestibulum ante ipsum primis</a><span>$12.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">In faucibus orci luctus et</a><span>$22.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Lorem ipsum dolor</a><span>$25.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Praesent vestibulum molestie</a><span>$8.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nonummy hendrerit</a><span>$19.00</span><strong>&nbsp;</strong></li>
      </ul>
    </div>
  </div>
  <div class="col_1_of_3 span_1_of_3">
    <div class="inner-block">
      <h3 class="top-2">Consectetuer</h3>
      <ul class="list-1 top-1">
        <li><a href="#">Lorem ipsum dolor</a><span>$25.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Praesent vestibulum molestie</a><span>$8.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nonummy hendrerit</a><span>$19.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Porta fusce suscipit varius miursu</a><span>$21.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Etiam cursus leo vel metus</a><span>$15.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nec eros</a><span>$9.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Vestibulum ante ipsum primis</a><span>$12.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">In faucibus orci luctus et</a><span>$22.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Lorem ipsum dolor</a><span>$25.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Praesent vestibulum molestie</a><span>$8.00</span><strong>&nbsp;</strong></li>
        <li><a href="#">Aenean nonummy hendrerit</a><span>$19.00</span><strong>&nbsp;</strong></li>
      </ul>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/contents/_content_product.html.erb
<div class="prod">
  <%= render "elements/product_item" %>
  <%= render "elements/product_item" %>
  <%= render "elements/product_item" %>
  <div class="clear"></div>
</div>

app/views/contents/_content_top.html.erb
<div class="content-top">
  <div class="col_1_of_5 span_1_of_5">
    <div class="hover_img">
      <img src="images/pic.jpg" alt=""/>
    </div>
  </div>
  <div class="col_1_of_5 span_1_of_5">
    <div class="hover_img">
	  <img src="images/pic1.jpg" alt=""/>
    </div>
  </div>
  <div class="col_1_of_5 span_1_of_5">
    <div class="hover_img">
      <img src="images/pic2.jpg" alt=""/>
    </div>
  </div>
  <div class="col_1_of_5 span_1_of_5">
    <div class="hover_img">
      <img src="images/pic3.jpg" alt=""/>
    </div>
  </div>
  <div class="col_1_of_last span_1_of_5">
    <h3><span class="red">Our Four</span><br><span class="black"> Food Types</span></h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad.</p>
  </div>
  <div class="clear"></div>
</div>

app/views/elements/_food_item.html.erb
<div class="col_1_of_4 span_1_of_4">
    <img src="images/glass.png" alt=""/>
      <h3><%= prod.title %></h3>
      <p><%= prod.description %></p>
  <button class="btn1 btn-8 btn-8a">Read More</button>
</div>

app/views/elements/_product_item.html.erb
<div class="col_1_of_3 span_1_of_3">
  <div class="view effect">
    <img src="images/pic9.jpg" alt=""/>
    <div class="mask"></div>
    <div class="content">
      <a href="<%= prod.picture %>" class="info" title="Full Image">Full Image</a>
    </div>
  </div>
  <h3><%= prod.title %></h3>
  <p><%= prod.description %></p>
  <button class="btn1 btn-8 btn-8a" onclick="window.location.href='<%= product_path(prod) %>'">Details</button>
  <button class="btn1 btn-8 btn-8a">Add to cart</button>
</div>

app/views/layouts/_banner.html.erb
<div class="banner">
  <div class="flexslider">
    <ul class="slides">
      <li><img src="<%=root_path%>images/banner1.jpg" alt=""/></li>
      <li><img src="<%=root_path%>images/banner2.jpg"  alt=""/></li>
      <li><img src="<%=root_path%>images/banner3.jpg"  alt=""/></li>
      <li><img src="<%=root_path%>images/banner4.jpg"  alt=""/></li>
    </ul>
  </div>
  <div class="flex-caption">
    <h2><a href="">Fast Food Seasonings</a></h2>
    <div class="clear"></div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-bottom">
  <div class="wrap">
    <div class="copy">
      <p> © 2013 All rights Reserved | Design by <a href="http://w3layouts.com">W3Layouts</a></p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header_top_right">
  <% unless user_signed_in? %>
    <ul>
      <li><%= link_to "Sign Up", new_user_registration_path %></li> |
      <li><%= link_to "Log In", new_user_session_path %></li> |
      <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>|
      <li><%= link_to "Thong tin ca nhan", user_path(current_user) %></li>|
      <% if current_user.store%>
        <li><%= link_to "Quan ly cua hang", store_path(current_user.store) %></li>
      <% else %>
        <li><%= link_to "Tao cua hang", new_store_path %></li>
      <% end %>
    </ul>
  <% end %>
  </div>
  <div class="clear"></div>
    <div class="header-bot">
      <div class="logo">
        <a href=<%= home_path %>><img src="<%=root_path%>images/logo.png" alt=""/></a>
      </div>
      <ul class="follow_icon">
        <li><a href="#"><img src="<%=root_path%>images/fb.png" alt=""></a></li>
        <li><a href="#"><img src="<%=root_path%>images/googleplus.png" alt=""></a></li>
        <li><a href="#"><img src="<%=root_path%>images/tw.png" alt=""></a></li>
        <li><a href="#"><img src="<%=root_path%>images/pinterest.png" alt=""></a></li>
      </ul>
      <div class="clear"></div>
    </div>
  <div class="search-bar">
    <input type="text" class="textbox" value=" Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
    <input name="searchsubmit" type="image" src="<%=root_path%>images/search-icon.png" value="Go" id="searchsubmit" class="btn">
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</div>

app/views/layouts/_menu.html.erb
<div class="menu">
    <div class="top-nav">
      <ul>
        <li class="active"><a href="home.html">Home</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="products.html">Products</a></li>
        <li><a href="pricing.html">Pricing</a></li>
        <li><a href="products.html">Delivery</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    <div class="clear"></div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDrinksApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrap">
       <div class="total">
         <%= render "layouts/header"%>
		     <%= render "layouts/menu" %>
         <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>
		     <div class="main">
		 	     <div class="content">
             <%= yield %>
		 	     </div>
		     </div>
       </div>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "contents/about_top" %>
<%= render "contents/content_top" %>
<%= render "contents/content_middle" %>
<%= render "contents/content_bottom" %>
<%= render "contents/content_last" %>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<%= render "contents/content_top" %>
<%= render "contents/content_middle" %>
<%= render "contents/content_bottom" %>
<%= render "contents/content_last" %>

app/views/pages/pricing.html.erb
<%= render "contents/content_example" %>
<%= render "contents/content_pricing" %>
<%= render "contents/content_last" %>

app/views/pages/products.html.erb
<%= render "contents/content_product" %>
<%= render "contents/content_last" %>

app/views/products/index.html.erb
<div class="content-last">
  <% @products.each do |prod| %>
  <%= render "elements/product_item", prod: prod %>
  <% end %>
  <div class="clear"></div>
</div>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<div class="content_bottom">
  <div class="container">
  <div class="card">
    <div class="container-fluid">
      <div class="wrapper row">
        <div class="preview col-md-6">
          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1"><img src="http://placekitten.com/200/126" /></div>
            <div class="tab-pane" id="pic-2"><img src="http://placekitten.com/200/126"" /></div>
            <div class="tab-pane" id="pic-3"><img src="http://placekitten.com/200/126"" /></div>
            <div class="tab-pane" id="pic-4"><img src="http://placekitten.com/200/126"" /></div>
            <div class="tab-pane" id="pic-5"><img src="http://placekitten.com/200/126"" /></div>
          </div>
          <ul class="preview-thumbnail nav nav-tabs">
            <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
            <li><a data-target="#pic-2" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
            <li><a data-target="#pic-3" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
            <li><a data-target="#pic-4" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
            <li><a data-target="#pic-5" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
          </ul>
        </div>
        <div class="details col-md-6">
          <h3 class="product-title">men's shoes fashion</h3>
          <div class="rating">
            <div class="stars">
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
            </div>
            <span class="review-no">41 reviews</span>
          </div>
          <p class="product-description">Suspendisse quos? Tempus cras iure temporibus? Eu laudantium cubilia sem sem! Repudiandae et! Massa senectus enim minim sociosqu delectus posuere.</p>
          <h4 class="price">current price: <span>$180</span></h4>
          <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>

          <div class="action">
            <button class="add-to-cart btn btn-default" type="button">add to cart</button>
              <button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_error.html.erb
<div class="page-not-found">
  <h1>404</h1>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>